# Generated by Django 4.1.6 on 2023-02-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('in process', 'in process'), ('completed', 'completed'), ('canceled', 'canceled')], max_length=50, null=True),
        ),
    ]
