# Generated by Django 4.1.6 on 2023-02-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sub_category',
            field=models.CharField(choices=[('python', 'python'), ('js', 'js'), ('c++', 'c++'), ('java', 'java'), ('c#', 'c#')], max_length=50),
        ),
    ]
