# Generated by Django 4.1.6 on 2023-02-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh', 'Chinese'), ('es', 'Spanish'), ('hi', 'Hindi'), ('ar', 'Arabic'), ('bn', 'Bengali'), ('ru', 'Russian'), ('pt', 'Portuguese'), ('id', 'Indonesian'), ('fr', 'French'), ('ur', 'Urdu'), ('ja', 'Japanese'), ('de', 'German'), ('pa', 'Punjabi'), ('jv', 'Javanese'), ('te', 'Telugu'), ('wuu', 'Wu Chinese'), ('mr', 'Marathi'), ('ko', 'Korean'), ('vi', 'Vietnamese'), ('ta', 'Tamil'), ('tr', 'Turkish'), ('it', 'Italian'), ('yue', 'Cantonese'), ('th', 'Thai'), ('gu', 'Gujarati'), ('pl', 'Polish'), ('uk', 'Ukrainian'), ('fa', 'Persian'), ('ro', 'Romanian'), ('ms', 'Malay'), ('uz', 'Uzbek'), ('hak', 'Hakka'), ('hu', 'Hungarian'), ('or', 'Odia'), ('bg', 'Bulgarian'), ('si', 'Sinhala'), ('ceb', 'Cebuano'), ('am', 'Amharic'), ('my', 'Burmese'), ('hr', 'Croatian'), ('az', 'Azerbaijani'), ('nl', 'Dutch'), ('sr', 'Serbian'), ('min', 'Minangkabau'), ('su', 'Sundanese'), ('fi', 'Finnish'), ('taq', 'Tamasheq'), ('cs', 'Czech'), ('el', 'Greek'), ('he', 'Hebrew')], max_length=20),
        ),
        migrations.AlterField(
            model_name='courseitemfile',
            name='file',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
