# Generated by Django 4.1.6 on 2023-02-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseitemfile',
            name='files',
            field=models.FileField(upload_to='files/'),
        ),
    ]
