# Generated by Django 4.1.6 on 2023-02-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_courseitemfile_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
