# Generated by Django 4.1.6 on 2023-02-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
