# Generated by Django 4.1.6 on 2023-02-14 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_password_reset_requested_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=20)),
                ('site_url', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=50, null=True)),
                ('youtube_url', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.CharField(blank=True, max_length=150, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_hidden_courses', models.BooleanField(default=False)),
                ('promotions', models.BooleanField(default=False)),
                ('mentor_ads', models.BooleanField(default=False)),
                ('email_ads', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
